const actionTypes = {
    "CLEAR_CANDIDAATE_MOVES" : "CLEAR_CANDIDAATE_MOVES",
    "GENERATE_CANDIDATE_MOVES" : "GENERATE_CANDIDATE_MOVES",
    "NEW_MOVE" : "NEW_MOVE",
    "PROMOTION_OPEN" : "PROMOTION_OPEN",
    "PROMOTION_CLOSE" : "PROMOTION_CLOSE",
    "CAN_CASTLE" : 'CAN_CASTLE'
}

export default actionTypes